# Generated by Django 4.1 on 2022-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_details',
            name='total',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_purchase_details',
            name='total',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='temp_purchase_details',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
