# Generated by Django 4.1 on 2022-09-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0001_initial'),
        ('purchase_master', '0002_purchase_details_total_temp_purchase_details_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_details',
            name='item_id',
        ),
        migrations.AddField(
            model_name='purchase_details',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item_master.item_master'),
            preserve_default=False,
        ),
    ]
