# Generated by Django 4.1 on 2022-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('stampdatetime', models.DateField(auto_now=True)),
                ('item_name', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'item_master',
            },
        ),
    ]
