# Generated by Django 5.0.7 on 2024-07-31 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.IntegerField()),
                ('transfer_date', models.DateField()),
                ('customer_id', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('sale_date', models.DateField(auto_now=True)),
                ('customer_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sale_master',
            },
        ),
        migrations.CreateModel(
            name='Temp_sale_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('stampdatetime', models.DateField(auto_now=True)),
                ('item_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'temp_sale_details',
            },
        ),
        migrations.CreateModel(
            name='Sale_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('stampdatetime', models.DateField(auto_now=True)),
                ('item_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_master.sale_master')),
            ],
            options={
                'db_table': 'sale_details',
            },
        ),
    ]
