# Generated by Django 4.1 on 2022-09-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
