# Generated by Django 4.1 on 2022-09-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier_master',
            table='supplier_master',
        ),
    ]
