# Generated by Django 4.1 on 2022-09-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_master', '0002_alter_supplier_master_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_master',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
